spring:
  profiles:
    active: local
---
chunhodong:
  property-breaker:
    hibernate-ddlauto-deactive: true
    general-property-deactive:
      key: server.port
      value: 3001
server:
  port: 3001
spring:
  config:
    activate:
      on-profile: local